version: '3.8'
services:
  monitor:
    container_name: monitor
    # image: monitor:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    ports:
      - 3003:80
    restart: unless-stopped
    networks:
      - local
networks:
  local:
